name: Build Docker image

on:
  workflow_call:
    inputs:
      MD_LINUX_FLAVOUR:
        required: true
        type: string
      MD_LINUX_UPSTREAM_VERSION:
        required: true
        type: string

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ inputs.MD_LINUX_FLAVOUR }}
          tags: |
            type=sha,event=push,enable=true,prefix=${{ inputs.MD_LINUX_UPSTREAM_VERSION }}-git-,format=short
            type=raw,event=push,enable={{ is_default_branch }},value=${{ inputs.MD_LINUX_UPSTREAM_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "{context}/Dockerfile.${{ inputs.MD_LINUX_FLAVOUR }}"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          provenance: false
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            UPSTREAM_VERSION=${{ inputs.MD_LINUX_UPSTREAM_VERSION }}
