on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  schedule:
    - cron: "0 10 * * 1"

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  debian:
    strategy:
      matrix:
        DEBIAN_VERSION: [ "bullseye", "bookworm" ]

    uses: "./.github/workflows/common.yml"
    secrets: "inherit" # for Docker image publication
    with:
      MD_LINUX_FLAVOUR: "debian"
      MD_LINUX_UPSTREAM_VERSION: "${{ matrix.DEBIAN_VERSION }}"
